<?php



namespace App\Console\Commands;



use Illuminate\Console\Command;



class SyncPermissionsFrontendCommand extends Command

{

    protected $signature = 'hub:sync-permissions-frontend';



    protected $description = 'Gera tipos TypeScript de roles, permissoes e navegacao para o frontend';



    public function handle(): int

    {

        $roles = array_keys(config('permissions.roles', []));

        $rolePermissions = config('permissions.role_permissions', []);

        $permissionKeys = [];



        foreach ($rolePermissions as $permissions) {

            foreach ($permissions as $permission) {

                $permissionKeys[$permission] = true;

            }

        }



        foreach (config('permissions.nav_permissions', []) as $moduleItems) {

            foreach ($moduleItems as $item) {

                if (! empty($item['key'])) {

                    $permissionKeys[$item['key']] = true;

                }

            }

        }



        $permissionKeys = array_keys($permissionKeys);

        sort($roles);

        sort($permissionKeys);



        $rolesExport = implode(",\n  ", array_map(fn (string $role) => "'{$role}'", $roles));

        $permissionsExport = implode(",\n  ", array_map(fn (string $key) => "'{$key}'", $permissionKeys));



        $keysContent = <<<TS

// Auto-generated by php artisan hub:sync-permissions-frontend — do not edit manually.

export const HUB_ROLE_KEYS = [

  {$rolesExport},

] as const



export const HUB_PERMISSION_KEYS = [

  {$permissionsExport},

] as const



export type HubRoleKey = (typeof HUB_ROLE_KEYS)[number]

export type HubPermissionKey = (typeof HUB_PERMISSION_KEYS)[number]



TS;



        $navItems = config('permissions.nav_items', []);

        $manifestEntries = [];

        $routeMaps = [];



        foreach ($navItems as $module => $items) {

            $moduleItems = [];

            $routeMap = [];



            foreach ($items as $item) {

                $key = $item['key'] ?? '';

                $to = $item['to'] ?? '';

                $icon = $item['icon'] ?? 'LayoutDashboard';

                $end = ! empty($item['end']) ? 'true' : 'false';

                $permission = $item['permission'] ?? $key;



                if ($key === '' || $to === '') {

                    continue;

                }



                $permissionExport = $this->exportPermissionValue($permission);

                $moduleItems[] = "    { key: '{$key}', to: '{$to}', icon: '{$icon}', end: {$end}, permission: {$permissionExport} }";

                $routeMap[$to] = $permission;

            }



            $manifestEntries[$module] = implode(",\n", $moduleItems);

            $routeMaps[$module] = $this->exportRouteMap($routeMap);

        }



        $manifestBlocks = [];

        foreach ($manifestEntries as $module => $entries) {

            $constName = strtoupper($module).'_NAV_MANIFEST';

            $manifestBlocks[] = "export const {$constName} = [\n{$entries}\n] as const";

        }



        $routeBlocks = [];

        foreach ($routeMaps as $module => $map) {

            $constName = $module.'RoutePermissions';

            $routeBlocks[] = "export const {$constName}: RoutePermissionMap = {$map} as const";

        }



        $navContent = "// Auto-generated by php artisan hub:sync-permissions-frontend — do not edit manually.\n"

            ."import type { HubPermissionKey } from './permissionKeys'\n\n"

            ."export type NavManifestItem = {\n"

            ."  key: string\n"

            ."  to: string\n"

            ."  icon: string\n"

            ."  end?: boolean\n"

            ."  permission: HubPermissionKey | readonly HubPermissionKey[]\n"

            ."}\n\n"

            ."export type RoutePermissionValue = HubPermissionKey | readonly HubPermissionKey[]\n"

            ."export type RoutePermissionMap = Record<string, RoutePermissionValue>\n\n"

            .implode("\n\n", $manifestBlocks)

            ."\n\n"

            .implode("\n\n", $routeBlocks)

            ."\n";



        $targetDir = base_path('../frontend/src/generated');

        if (! is_dir($targetDir)) {

            mkdir($targetDir, 0755, true);

        }



        $keysPath = $targetDir.'/permissionKeys.ts';

        $navPath = $targetDir.'/navManifest.ts';



        file_put_contents($keysPath, $keysContent);

        file_put_contents($navPath, $navContent);



        $this->info("Gerado: {$keysPath}");

        $this->info("Gerado: {$navPath}");



        return self::SUCCESS;

    }



    private function exportPermissionValue(string|array $permission): string

    {

        if (is_array($permission)) {

            $items = array_map(fn (string $p) => "'{$p}'", $permission);



            return '['.implode(', ', $items).']';

        }



        return "'{$permission}'";

    }



    /**

     * @param  array<string, string|list<string>>  $routeMap

     */

    private function exportRouteMap(array $routeMap): string

    {

        $lines = [];

        foreach ($routeMap as $route => $permission) {

            $lines[] = "  '{$route}': ".$this->exportPermissionValue($permission);

        }



        return "{\n".implode(",\n", $lines)."\n}";

    }

}

