import type { LucideIcon } from 'lucide-react'
import {
  BarChart3,
  BookOpen,
  Calendar,
  CalendarCheck,
  ClipboardList,
  Contact,
  DoorOpen,
  FileSpreadsheet,
  FileText,
  GraduationCap,
  LayoutDashboard,
  ListTodo,
  MapPin,
  Package,
  School,
  Signpost,
  UserCheck,
  Users,
  Wallet,
} from 'lucide-react'

export const NAV_ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Contact,
  GraduationCap,
  Users,
  School,
  BookOpen,
  Calendar,
  CalendarCheck,
  ClipboardList,
  FileText,
  MapPin,
  FileSpreadsheet,
  Wallet,
  Signpost,
  ListTodo,
  BarChart3,
  Package,
  UserCheck,
  DoorOpen,
}
